phases:
- phase: Windows
  queue: Hosted VS2017
    parallel: 2
    matrix:
      x64_release:
        buildArch: x64
        buildConfig: release
      x86_release:
        buildArch: x86
        buildConfig: release
  steps:
  - script: echo hello from Windows
  - script: build arch=$(buildArch) config=$(buildConfig)

- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - script: echo hello from macOS
  - script: build arch=$(buildArch) config=$(buildConfig)

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - script: echo hello from Linux
  - script: build arch=$(buildArch) config=$(buildConfig)

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

# queue:
#   parallel: 2 # Limit to two agents at a time
#   matrix:
#     x64_release:
#       queue: Hosted VS2017
#       buildArch: x64
#       buildConfig: release
#     x86_release:
#       queue: Hosted VS2017
#       buildArch: x86
#       buildConfig: release
#     linux:
#       queue: Hosted Linux Preview
#       buildArch: x64
#       buildConfig: release
#     mac:
#       queue: Hosted macOS Preview
#       buildArch: x64
#       buildConfig: release
#steps:
#- script: build arch=$(buildArch) config=$(buildConfig)



# steps:

# - script: |
#     echo hello world from %MyName%
#     echo Agent.HomeDirectory is %CD%
#   workingDirectory: $(Agent.HomeDirectory)
#   env:
#     MyName: $(Agent.MachineName)
#   condition: and(succeeded(), eq(variables['agent.os'], 'windows_nt'))
#   displayName: Greeting from Windows machine

# - script: |
#     echo hello world from $MyName
#     echo Agent.HomeDirectory is $PWD
#   workingDirectory: $(Agent.HomeDirectory)
#   env:
#     MyName: $(Agent.MachineName)
#   condition: and(succeeded(), in(variables['agent.os'], 'darwin', 'linux'))
#   displayName: Greeting from macOS or Linux machine
